### ISSUE TITLE
Switching to JSON

### ISSUE THREAD

**Issue by rjawesome** [Team-Optix-3749/Optix-Scouting#4]
May be a good idea to switch to JSON because it would be easier to read by computers, easier to store lists, and doesn't require any newlines. Could be impllemented with compression if necessary.

**Comment by nVarap** [comment]
By this you mean switch the data transmission to JSON?

**Comment by rjawesome** [comment]
Data transmission and file storage

**Comment by rjawesome** [comment]
Done by 8562c66d943162f42d282a31ca9756e3047726f6 and 7bd2ba5fd62e90ee1e138120dae18e7c5414e523
